import {image,imageStack,caption,icon} from './shared.js';
import {renderProductCard} from './product-card.js';
export function renderScreen(m,header=''){if(m.layout==='split')return m.panels.map(p=>`<div class="panel">${imageStack(p,p.title,true)}${caption(p)}</div>`).join('');return imageStack(m,m.title,m.layout==='hero')+header+caption(m)}
export function renderVideo(m){return `<video class="screen-video" autoplay muted loop playsinline preload="metadata" poster="${m.poster}" aria-label="${m.title}"><source src="${m.video}" type="video/mp4"></video>${caption(m)}`}
export function renderGrid(m){return `<div class="grid">${m.items.map(p=>{const tag=m.layout==='products'?'a':'div';const href=m.layout==='products'?` href="products.html?category=${encodeURIComponent(p.title.toLowerCase())}"`:'';return `<${tag}${href} class="card"><div class="card-image">${imageStack(p,p.title)}</div><div class="card-label"><h2>${p.title}</h2>${m.layout==='stories'?`<span class="text-link">${p.link||'DISCOVER'}</span>`:''}</div></${tag}>`}).join('')}</div>${m.layout==='products'?'<a class="view-more text-link" href="products.html">VIEW ALL</a>':''}`}
export function renderBestsellers(m){const cards=m.items.map(p=>renderProductCard({image:p.image,title:p.title||'Mile Skirt in Black',price:p.price||'£395',colors:p.colors||['#45352d','#5b2834','#f3f1f9'],badge:'NEW IN',className:'bestseller-card'})).join('');return `<div class="bestseller-heading"><h2>${m.title}</h2><span class="text-link">${m.link}</span></div><div class="bestseller-viewport"><div class="bestseller-track"><div class="bestseller-set">${cards}</div><div class="bestseller-set" aria-hidden="true">${cards}</div></div></div>`}
export function renderPromotion(m){return `<img class="promotion-image" src="${m.image}" alt=""><div class="promotion-shade" aria-hidden="true"></div><div class="promotion-copy"><p>${m.eyebrow}</p><div><h2>${m.title}</h2><p>${m.subtitle}</p></div><span>${m.link}</span></div>`}
export function renderServices(){const items=[['return-new','Free Returns','All full-priced orders can be returned or exchanged within 14 days'],['box-new','Worldwide Shipping','Delivery options and fees are shown at checkout.'],['client-service-new','Client Service','Our team is here to assist with your order and styling questions.']];return items.map(([asset,title,copy])=>`<div class="service"><span class="service-icon">${icon(asset,'')}</span><div class="service-copy"><h3>${title}</h3><p>${copy}</p></div><span class="service-chevron">${icon('chevron-new','')}</span></div>`).join('')}
export function renderSocial(m){return `<h2 class="social-heading">${m.title}</h2><div class="social-grid">${m.items.map((item,index)=>`<div class="social-card social-card-${index+1}" tabindex="0"><img src="${item.image}" alt="TU community look ${index+1}"><span>LEARN MORE</span></div>`).join('')}</div>`}
